Ticket#101 Axios version update to fix high severity security warning
NCIOCPL/drug-dictionary-app pull request #102
Opened 2021-01-08 20:46 UTC by alerosad

(#101) Axios version update to fix high severity security warning 
Updated axios version along with listed packages:

npm update ini --depth 4
npm install --save-dev start-server-and-test@1.11.7
npm install axios@0.21.1
npm install --save-dev resolve-url-loader@3.1.2

2021-01-08 21:47 UTC, blairlearn requested changes
You're getting closer.

The commit comment should be:

```
(#101) Updated axios version along with listed packages

npm update ini --depth 4
npm install --save-dev start-server-and-test@1.11.7
npm install axios@0.21.1
npm install --save-dev resolve-url-loader@3.1.2
```

2021-01-08 21:52 UTC, blairlearn requested changes
This comment intentionally blank.

2021-01-11 15:45 UTC, kate-mashkina approved these changes

2021-02-02 15:20 UTC, alerosad commented
https://react-app-dev.cancer.gov/drug-dictionary-app/pr-102/ @mworrest @blilianyu @lburack

2021-02-02 23:07 UTC, lburack commented
The app module looks good to me! CC @mworrest @blilianyu

2021-02-03 14:08 UTC, arcepaul approved these changes

2021-02-03 14:09 UTC, merged